<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SKT1112049PN002" name="NUGUAPP_002_연결.연결_03_NUGU_candle" tests="18" failures="0" timestamp="12 Oct 2020 06:19:41 GMT" time="120.136" errors="1">
  <testcase name="TC_연결_137" time="3.719" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_131" time="2.417" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_133" time="6.397" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_125" time="3.972" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_127" time="1.786" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_135" time="3.516" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_136" time="7.546" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_124" time="2.815" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_149" time="1.585" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_123" time="27.844" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_151" time="16.230" classname="NUGUAPP_002_연결.연결_03_NUGU_candle">
    <error type="org.testng.SkipException" message="연결 가능한 디바이스 있음. Test Skip">
      <![CDATA[org.testng.SkipException: 연결 가능한 디바이스 있음. Test Skip
	at NUGUAPP_002_연결.연결_03_NUGU_candle.TC_연결_151(연결_03_NUGU_candle.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TC_연결_151 -->
  <testcase name="TC_연결_150" time="2.164" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_138" time="2.944" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_154_form_155" time="14.019" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_139" time="5.389" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_134" time="2.535" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_126" time="4.217" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
  <testcase name="TC_연결_128_form_130" time="11.041" classname="NUGUAPP_002_연결.연결_03_NUGU_candle"/>
</testsuite> <!-- NUGUAPP_002_연결.연결_03_NUGU_candle -->
